# https://dart.dev/tools/pub/pubspec
name: unlimited
version: 0.0.1+1
description: Cards database and game rules for the Star Wars Unlimited CCG.

environment:
  sdk: ^3.1.0

repository: https://github.com/matanlurey/unlimited
issue_tracker: https://github.com/matanlurey/unlimited/issues
topics:
  - star-wars

dependencies:
  collection: ^1.18.0
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.6
